name: "Magento 2 Coding Standard"
author: "Codemanufacture"
description: "Performs static code analysis with Magento 2 Coding Standard"
inputs:
  standard:
    description: "The name or path of the coding standard to use"
    required: true
    default: "Magento2"
  report_style:
    required: false
    default: "checkstyle"
  severity:
    description: "The minimum severity required to display an error or warning"
    required: false
  warning_severity:
    description: "The minimum severity required to display warning"
    required: false
  error_severity:
    description: "The minimum severity required to display an error"
    required: false
  verbosity:
    description: "Code Sniffer verbosity"
    required: false
    default: ""
  phpcs_path:
    description: "Path to PHP_CodeSniffer binary"
    required: true
    default: 'phpcs'
  install_coding_standard:
    description: "Installs coding standard"
    required: false
    default: true
  coding_standard_version:
    description: "Coding standard version"
    required: false
    default: "*"
  coding_standard_package:
    description: "Coding standard package name"
    required: false
    default: "magento/magento-coding-standard"
  directory:
    description: "Working directory where analysis is run"
    required: false
    default: ${{ github.workspace }}
  processes:
    description: "How many files should be checked simultaneously"
    required: false
    default: 1
  extensions:
    description: "A comma separated list of file extensions to check"
    required: false
    default: "php"
  ignore_warnings_on_exit:
    required: false
    default: 0
  ignore_errors_on_exit:
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - name: Installing coding standard
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      if: ${{ inputs.install_coding_standard }}
      run: ${{ github.action_path }}/src/install_coding_standard.bash
    - name: Check if phpcs exists
      shell: bash
      run: ${{ inputs.phpcs_path }} --version
    - name: Add problem matchers
      shell: bash
      run:
        echo "::add-matcher::${{ github.action_path }}/problem-matcher.json"
    - shell: bash
      run: ${{ github.action_path }}/src/run_coding_standard.sh
branding:
  icon: 'check-square'
  color: 'blue'
