name: "Magento 2 coding standard analysis with PHP_CodeSniffer"
author: "Codemanufacture"
description: "Performs static code analysis with PHP_CodeSniffer and Magento 2 coding standard by default"
inputs:
  standard:
    description: "The name or path of the coding standard to use"
    required: true
    default: "Magento2"
  report_style:
    required: false
    default: "checkstyle"
  severity:
    description: "The minimum severity required to display an error or warning"
    required: false
  warning_severity:
    description: "The minimum severity required to display warning"
    required: false
  error_severity:
    description: "The minimum severity required to display an error"
    required: false
  verbosity:
    description: "Code Sniffer verbosity"
    required: false
    default: ""
  phpcs_path:
    description: "Path to PHP_CodeSniffer binary"
    required: true
    default: 'phpcs'
  install_coding_standard:
    description: "Installs coding standard"
    required: false
    default: true
  coding_standard_version:
    description: "Coding standard version"
    required: false
    default: "*"
  coding_standard_package:
    description: "Coding standard package name"
    required: false
    default: "magento/magento-coding-standard"
  file_list:
    description: "Working directory or file list to analyse"
    required: false
    default: ${{ github.workspace }}
  processes:
    description: "How many files should be checked simultaneously"
    required: false
    default: 1
  extensions:
    description: "A comma separated list of file extensions to check"
    required: false
    default: "php"
  ignore_warnings_on_exit:
    required: false
    default: 0
  ignore_errors_on_exit:
    required: false
    default: 0
  ignore:
    description: "A comma separated list of patterns to ignore files and directories"
    required: false
runs:
  using: "composite"
  steps:
    - name: Installing coding standard
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_CODING_STANDARD_PACKAGE: ${{ inputs.coding_standard_package }}
        INPUT_CODING_STANDARD_VERSION: ${{ inputs.coding_standard_version }}
      if: ${{ inputs.install_coding_standard }}
      run: ${{ github.action_path }}/src/install_coding_standard.bash
    - name: Check if phpcs exists
      shell: bash
      run: ${{ inputs.phpcs_path }} --version
    - name: Add problem matchers
      shell: bash
      run:
        echo "::add-matcher::${{ github.action_path }}/problem-matcher.json"
    - name: Limit files in pull request
      shell: bash
      id: pr-files
      run: echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
      if: github.event_name == 'pull_request'
    - name: Running coding standard analysis
      shell: bash
      run: ${{ github.action_path }}/src/run_coding_standard.bash
      env:
        INPUT_SEVERITY: ${{ inputs.severity }}
        INPUT_ERROR_SEVERITY: ${{ inputs.error_severity }}
        INPUT_WARNING_SEVERITY: ${{ inputs.warning_severity }}
        INPUT_FILE_LIST: ${{ github.event_name == 'pull_request' && steps.pr-files.outputs.files || inputs.file_list }}
        INPUT_PHPCS_PATH: ${{ inputs.phpcs_path }}
        INPUT_IGNORE_ERRORS_ON_EXIT: ${{ inputs.ignore_errors_on_exit }}
        INPUT_IGNORE_WARNINGS_ON_EXIT: ${{ inputs.ignore_warnings_on_exit }}
        INPUT_EXTENSIONS: ${{ inputs.extensions }}
        INPUT_PROCESSES: ${{ inputs.processes }}
        INPUT_STANDARD: ${{ inputs.standard }}
        INPUT_VERBOSITY: ${{ inputs.verbosity }}
        INPUT_REPORT_STYLE: ${{ inputs.report_style }}
        INPUT_IGNORE: ${{ inputs.ignore }}
branding:
  icon: 'check-square'
  color: 'blue'
