name: "Magento 2 Coding Standard Demo"
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  push:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: codemanufacture/magento2-dummy-module
        ref: main
        path: module
    - name: Setup PHP with composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer:2.3, phpcs:3.6
    - name: Run coding standard analysis
      uses: ./
      with:
        file_list: "${{github.workspace}}/module"
        severity: 5
        ignore_errors_on_exit: 1
        ignore_warnings_on_exit: 1
